/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingRouteImport } from './routes/landing'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUnlockRouteImport } from './routes/_app/unlock'
import { Route as AppTimelineRouteImport } from './routes/_app/timeline'
import { Route as AppSetupRouteImport } from './routes/_app/setup'
import { Route as AppMigrateRouteImport } from './routes/_app/migrate'
import { Route as AppEntryNewRouteImport } from './routes/_app/entry/new'
import { Route as AppEntryIdIndexRouteImport } from './routes/_app/entry/$id/index'
import { Route as AppEntryIdEditRouteImport } from './routes/_app/entry/$id/edit'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingRoute = LandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUnlockRoute = AppUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppSetupRoute = AppSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AppRoute,
} as any)
const AppMigrateRoute = AppMigrateRouteImport.update({
  id: '/migrate',
  path: '/migrate',
  getParentRoute: () => AppRoute,
} as any)
const AppEntryNewRoute = AppEntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => AppRoute,
} as any)
const AppEntryIdIndexRoute = AppEntryIdIndexRouteImport.update({
  id: '/entry/$id/',
  path: '/entry/$id/',
  getParentRoute: () => AppRoute,
} as any)
const AppEntryIdEditRoute = AppEntryIdEditRouteImport.update({
  id: '/entry/$id/edit',
  path: '/entry/$id/edit',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/migrate': typeof AppMigrateRoute
  '/setup': typeof AppSetupRoute
  '/timeline': typeof AppTimelineRoute
  '/unlock': typeof AppUnlockRoute
  '/entry/new': typeof AppEntryNewRoute
  '/entry/$id/edit': typeof AppEntryIdEditRoute
  '/entry/$id/': typeof AppEntryIdIndexRoute
}
export interface FileRoutesByTo {
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/migrate': typeof AppMigrateRoute
  '/setup': typeof AppSetupRoute
  '/timeline': typeof AppTimelineRoute
  '/unlock': typeof AppUnlockRoute
  '/': typeof AppIndexRoute
  '/entry/new': typeof AppEntryNewRoute
  '/entry/$id/edit': typeof AppEntryIdEditRoute
  '/entry/$id': typeof AppEntryIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/landing': typeof LandingRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/terms': typeof TermsRoute
  '/_app/migrate': typeof AppMigrateRoute
  '/_app/setup': typeof AppSetupRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/unlock': typeof AppUnlockRoute
  '/_app/': typeof AppIndexRoute
  '/_app/entry/new': typeof AppEntryNewRoute
  '/_app/entry/$id/edit': typeof AppEntryIdEditRoute
  '/_app/entry/$id/': typeof AppEntryIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/migrate'
    | '/setup'
    | '/timeline'
    | '/unlock'
    | '/entry/new'
    | '/entry/$id/edit'
    | '/entry/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/landing'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/migrate'
    | '/setup'
    | '/timeline'
    | '/unlock'
    | '/'
    | '/entry/new'
    | '/entry/$id/edit'
    | '/entry/$id'
  id:
    | '__root__'
    | '/_app'
    | '/landing'
    | '/login'
    | '/privacy'
    | '/terms'
    | '/_app/migrate'
    | '/_app/setup'
    | '/_app/timeline'
    | '/_app/unlock'
    | '/_app/'
    | '/_app/entry/new'
    | '/_app/entry/$id/edit'
    | '/_app/entry/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LandingRoute: typeof LandingRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing': {
      id: '/landing'
      path: '/landing'
      fullPath: '/landing'
      preLoaderRoute: typeof LandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/unlock': {
      id: '/_app/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AppUnlockRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/setup': {
      id: '/_app/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof AppSetupRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/migrate': {
      id: '/_app/migrate'
      path: '/migrate'
      fullPath: '/migrate'
      preLoaderRoute: typeof AppMigrateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entry/new': {
      id: '/_app/entry/new'
      path: '/entry/new'
      fullPath: '/entry/new'
      preLoaderRoute: typeof AppEntryNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entry/$id/': {
      id: '/_app/entry/$id/'
      path: '/entry/$id'
      fullPath: '/entry/$id/'
      preLoaderRoute: typeof AppEntryIdIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/entry/$id/edit': {
      id: '/_app/entry/$id/edit'
      path: '/entry/$id/edit'
      fullPath: '/entry/$id/edit'
      preLoaderRoute: typeof AppEntryIdEditRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppMigrateRoute: typeof AppMigrateRoute
  AppSetupRoute: typeof AppSetupRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppUnlockRoute: typeof AppUnlockRoute
  AppIndexRoute: typeof AppIndexRoute
  AppEntryNewRoute: typeof AppEntryNewRoute
  AppEntryIdEditRoute: typeof AppEntryIdEditRoute
  AppEntryIdIndexRoute: typeof AppEntryIdIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppMigrateRoute: AppMigrateRoute,
  AppSetupRoute: AppSetupRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppUnlockRoute: AppUnlockRoute,
  AppIndexRoute: AppIndexRoute,
  AppEntryNewRoute: AppEntryNewRoute,
  AppEntryIdEditRoute: AppEntryIdEditRoute,
  AppEntryIdIndexRoute: AppEntryIdIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LandingRoute: LandingRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
