/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryNewRouteImport } from './routes/entry/new'
import { Route as EntryIdRouteImport } from './routes/entry/$id'
import { Route as EntryIdEditRouteImport } from './routes/entry/$id.edit'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryNewRoute = EntryNewRouteImport.update({
  id: '/entry/new',
  path: '/entry/new',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryIdRoute = EntryIdRouteImport.update({
  id: '/entry/$id',
  path: '/entry/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryIdEditRoute = EntryIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => EntryIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/timeline': typeof TimelineRoute
  '/unlock': typeof UnlockRoute
  '/entry/$id': typeof EntryIdRouteWithChildren
  '/entry/new': typeof EntryNewRoute
  '/entry/$id/edit': typeof EntryIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/timeline': typeof TimelineRoute
  '/unlock': typeof UnlockRoute
  '/entry/$id': typeof EntryIdRouteWithChildren
  '/entry/new': typeof EntryNewRoute
  '/entry/$id/edit': typeof EntryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setup': typeof SetupRoute
  '/timeline': typeof TimelineRoute
  '/unlock': typeof UnlockRoute
  '/entry/$id': typeof EntryIdRouteWithChildren
  '/entry/new': typeof EntryNewRoute
  '/entry/$id/edit': typeof EntryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/timeline'
    | '/unlock'
    | '/entry/$id'
    | '/entry/new'
    | '/entry/$id/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/setup'
    | '/timeline'
    | '/unlock'
    | '/entry/$id'
    | '/entry/new'
    | '/entry/$id/edit'
  id:
    | '__root__'
    | '/'
    | '/setup'
    | '/timeline'
    | '/unlock'
    | '/entry/$id'
    | '/entry/new'
    | '/entry/$id/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupRoute: typeof SetupRoute
  TimelineRoute: typeof TimelineRoute
  UnlockRoute: typeof UnlockRoute
  EntryIdRoute: typeof EntryIdRouteWithChildren
  EntryNewRoute: typeof EntryNewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/new': {
      id: '/entry/new'
      path: '/entry/new'
      fullPath: '/entry/new'
      preLoaderRoute: typeof EntryNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$id': {
      id: '/entry/$id'
      path: '/entry/$id'
      fullPath: '/entry/$id'
      preLoaderRoute: typeof EntryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$id/edit': {
      id: '/entry/$id/edit'
      path: '/edit'
      fullPath: '/entry/$id/edit'
      preLoaderRoute: typeof EntryIdEditRouteImport
      parentRoute: typeof EntryIdRoute
    }
  }
}

interface EntryIdRouteChildren {
  EntryIdEditRoute: typeof EntryIdEditRoute
}

const EntryIdRouteChildren: EntryIdRouteChildren = {
  EntryIdEditRoute: EntryIdEditRoute,
}

const EntryIdRouteWithChildren =
  EntryIdRoute._addFileChildren(EntryIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupRoute: SetupRoute,
  TimelineRoute: TimelineRoute,
  UnlockRoute: UnlockRoute,
  EntryIdRoute: EntryIdRouteWithChildren,
  EntryNewRoute: EntryNewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
